import Copyright from "@/components/CopyRight";
import HeaderNav from "@/components/HeaderNav";
import SideNav from "@/components/sidenav";
import "@/styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode; 
}) {
  return (
        <div className="dashboardContainer overflow-y-scroll overflow-x-hidden">
        <HeaderNav activeView="users management" />
        <SideNav activeView="users management" />

        {children}


        <Copyright />

        </div>
  );
}